### ISSUE TITLE
某个文分发后，正文丢失

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-project-qhd#120]
https://qhd.steedos.com/workflow/space/Af8eM6mAHo7wMDqD3/monitor/H9LZT7PY9KHqfCWfB

![image](https://user-images.githubusercontent.com/15027092/78850895-f2ecdf80-7a4a-11ea-8e9b-42d475369c83.png)

**Comment by marchtian** [comment]
出错的文件已处理。
0410已更新正式环境，待后续跟踪还有无问题。

**Comment by marchtian** [comment]
出错的文件已处理。
0410已更新正式环境，待后续跟踪还有无问题。
