### ISSUE TITLE
qhd审批王中点击关联文件，搜索关键字会超时

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-project-qhd#44]

**Comment by sunhaolin** [comment]
dzug也有这个问题

**Comment by baozhoutao** [comment]
此问题是由于 "关联文件的任选范围，扩大到监控箱的文件 "https://github.com/steedos/workflow/issues/1950 任务导致
修改完成后，请将代码同步到creator的workflow

**Comment by marchtian** [comment]
1211 已更新
