### ISSUE TITLE
老档案，批量修改报错

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-project-qhd#79]
from： 股份办公室
![微信图片_20200109175934](https://user-images.githubusercontent.com/7553007/72058234-b655fe80-330a-11ea-802c-4a81ade1dbe2.jpg)

**Comment by baozhoutao** [comment]
问题要通过修改浏览器设置来处理。将档案网址先加入信任站点，然后自定义安全级别，找到 “启用XSS筛选器” 选择禁用 。确定后重启IE 就可以了。这个问题是 IE把我们传入的sql当作跨站点攻击了，IE自动修改了我们的sql脚本，把小括号换成#号了。

**Comment by marchtian** [comment]
办公室设置后，问题已解决
